Import('*')

#
#
#
cpppath = ['../src', '../third-party/gtest-1.7.0/include']
libpath = ['../third-party/gtest-1.7.0']
libs = ['gtest', 'pthread']

sources = Glob('*.cpp')
sources += Glob('../src/func.o')

ENV.Program('test', sources, CPPPATH=cpppath, LIBPATH=libpath, LIBS=libs)
