sudo: required
dist: trusty

language:
    - cpp
    
before_install:
    - sudo apt-get update
    - sudo apt-get install doxygen

compiler:
    - clang

script:
    - mkdir build
    - cd build
    - cmake --version
    - cmake ..
    - make
    - test/test-libmymath
