sudo: required
dist: trusty

language:
    - cpp

compiler:
    - gcc
    - clang

script:
    - mkdir build
    - cd build
    - cmake ..
    - make
    - test/test-libmymath
    - cd ../doc
    - doxygen

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen
