# sudo: required
# dist: trusty

language:
    - cpp

compiler:
    - gcc
    - clang

script:
    - scons && test/test && cd doc && doxygen

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen
