install:
    - git submodule init
    - git submodule update

before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" -Dgtest_force_shared_crt=on ..

build_script:
    - msbuild /v:minimal /p:Configuration=%CONFIGURATION% cpp-project-template.sln
 
test_script:
    - test\%CONFIGURATION%\test-libmymath.exe
    
os:
    - Visual Studio 2015

platform:
    - x64

configuration:
    - Debug
    - Release
