image:
    - Visual Studio 2019

configuration:
    - Debug
    - Release

install:
    - git submodule init
    - git submodule update

before_build:
    - mkdir build
    - cd build

build_script:
    - cmake -A Win64 -T v140 -Dgtest_force_shared_crt=on ..
    - cmake --build . --config %CONFIGURATION%
 
test_script:
    - test\%CONFIGURATION%\test-libmymath.exe
