before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" -Dgtest_force_shared_crt=on ..

build_script:
    - msbuild /p:Configuration=%CONFIGURATION% cpp-project-template.sln
 
after_build:
    - dir *.exe
 
#test_script:
#- x64\%CONFIGURATION%\test-libmymath.exe

platform:
    - x64

configuration:
    - Debug
    - Release
