before_build:
    - mkdir build
    - cd build
    - cmake -G "Visual Studio 14 2015 Win64" -Dgtest_force_shared_crt=on .

build:
    project: cpp-project-template.sln

platform:
    - x64

configuration:
    - Debug
    - Release
